module.exports = {
  User: require("./User"),
  Room: require("./Room"),
  RoomBooking: require("./RoomBooking"),
  Restaurant: require("./Restaurant"),
  Table: require("./Table"),
  TableBooking: require("./TableBooking"),
  FoodItem: require("./FoodItem"),
  FoodOrder: require("./FoodOrder"),
  Membership: require("./Membership"),
  MembershipTransaction: require("./MembershipTransaction"),
  SpaService: require("./SpaService"),
  SpaBooking: require("./SpaBooking"),
  Event: require("./Event"),
  EventBooking: require("./EventBooking"),
  Payment: require("./Payment"),
  Coupon: require("./Coupon"),
  Review: require("./Review"),
  Gallery: require("./Gallery"),
  Testimonial: require("./Testimonial"),
  Notification: require("./Notification"),
  ActivityLog: require("./ActivityLog"),
  Blog: require("./Blog"),
  Contact: require("./Contact"),
  Newsletter: require("./Newsletter"),
  Setting: require("./Setting")
};
